[package]
name = "shrike"
version = "0.0.0"
edition = "2021"
authors = ["Rodrigo Navarro <rnavarro@rnavarro.com.br>"]
license = "MIT"
repository = "https://github.com/reu/shrike"
categories = ["network-programming", "web-programming"]
keywords = ["http", "synchronous"]

[dependencies]
headers = "0.3.7"
http = "0.2.8"
httparse = "1.7.1"
thiserror = "1.0.31"
